### PR TITLE
Update CI to GHC 9.8

### PR DESCRIPTION
**Pull request by andreasabel**

### CODE REVIEW

**Comment by andreasabel** [comment]
@erikd : Can this be merged?

**Comment by erikd** [comment]
If you are happy with this, then sure.

My only concern is that some of the checks were cancelled.

**Comment by andreasabel** [comment]
@erikd: Well, if you look closely, the cancelled checks are copies of the non-cancelled ones.

The way the `on` triggers are set in the CI here is that on PRs everything runs twice, once because of _push_ and once because of _pull-request_.

That's why I cancel one of the runs.

**Comment by andreasabel** [comment]
@erikd: Sorry for the noise, I didn't see I am on my fork here.
This PR is already merged into the base repo.

**Pull request closed without merging**
